[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "ARC Robot Extension"
author = "Sol Choi"
maintainer = "Sol Choi"
description="ARC Robot Training for Isaac Lab"
repository = "https://github.com/S-CHOI-S/Humarconoid.git"
keywords = ["extension", "ARC", "humanoid", "RL", "isaaclab"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "arc_lab"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
